import type { CatalogSKU, Signal } from './types';

export const seedCatalog: CatalogSKU[] = [
  {
    id: 'sku-001',
    name: 'Starlink Enterprise',
    category: 'Connectivity',
    capabilities: [
      'High-speed satellite internet',
      'Global coverage',
      'Low latency',
      'Rapid deployment',
      'Secure communications',
      'Mobile connectivity',
    ],
    tags: ['satellite', 'internet', 'remote', 'mobile', 'secure', 'enterprise'],
    description: 'Enterprise-grade satellite internet service providing high-speed, low-latency connectivity for remote and mobile operations worldwide.',
    created_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'sku-002',
    name: 'SpaceX Launch Services',
    category: 'Transportation',
    capabilities: [
      'Heavy payload capacity',
      'Rapid turnaround',
      'Reusable systems',
      'Mission flexibility',
      'Government certification',
    ],
    tags: ['launch', 'space', 'payload', 'government', 'certified'],
    description: 'Reliable launch services for government and commercial payloads with proven track record and security clearances.',
    created_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'sku-003',
    name: 'Starshield Government Platform',
    category: 'Defense & Security',
    capabilities: [
      'Encrypted communications',
      'Earth observation',
      'Persistent coverage',
      'Multi-domain operations',
      'Custom payloads',
      'Classified networks',
    ],
    tags: ['defense', 'government', 'classified', 'secure', 'satellite', 'observation'],
    description: 'Dedicated government satellite network for defense and intelligence applications with end-to-end encryption and classified capability.',
    created_at: new Date('2024-01-20').toISOString(),
  },
  {
    id: 'sku-004',
    name: 'Dragon Cargo Services',
    category: 'Transportation',
    capabilities: [
      'ISS resupply',
      'Pressurized cargo',
      'Unpressurized cargo',
      'Return capability',
      'NASA certified',
    ],
    tags: ['cargo', 'space', 'ISS', 'NASA', 'transport'],
    description: 'Proven cargo delivery and return services to the International Space Station and other orbital destinations.',
    created_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'sku-005',
    name: 'Starlink Maritime',
    category: 'Connectivity',
    capabilities: [
      'Ocean coverage',
      'High-speed internet',
      'Weather resilient',
      'Easy installation',
      'Fleet management',
    ],
    tags: ['maritime', 'ocean', 'shipping', 'satellite', 'internet'],
    description: 'Satellite internet service optimized for maritime operations including Coast Guard and naval vessels.',
    created_at: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'sku-006',
    name: 'Starlink Aviation',
    category: 'Connectivity',
    capabilities: [
      'In-flight connectivity',
      'Low latency',
      'High bandwidth',
      'Global coverage',
      'Aviation certified',
    ],
    tags: ['aviation', 'aircraft', 'inflight', 'satellite', 'internet'],
    description: 'High-speed satellite internet for aircraft enabling reliable connectivity during flight operations.',
    created_at: new Date('2024-02-10').toISOString(),
  },
  {
    id: 'sku-007',
    name: 'Earth Observation Services',
    category: 'Intelligence',
    capabilities: [
      'High-resolution imaging',
      'Real-time data',
      'Global monitoring',
      'Change detection',
      'Analytics platform',
    ],
    tags: ['imaging', 'observation', 'surveillance', 'intelligence', 'analytics'],
    description: 'Satellite-based Earth observation and imagery services for monitoring, intelligence, and disaster response.',
    created_at: new Date('2024-02-15').toISOString(),
  },
  {
    id: 'sku-008',
    name: 'Emergency Response Network',
    category: 'Emergency Services',
    capabilities: [
      'Rapid deployment',
      'Disaster recovery',
      'Emergency communications',
      'First responder support',
      'Backup connectivity',
    ],
    tags: ['emergency', 'disaster', 'response', 'communications', 'backup'],
    description: 'Emergency satellite communication services for disaster response and first responder operations.',
    created_at: new Date('2024-02-20').toISOString(),
  },
];

export const seedSignals: Signal[] = [
  {
    id: 'sig-001',
    source: 'ICE RFI 2024-Q2',
    title: 'Immigration and Customs Enforcement Remote Connectivity RFI',
    summary: 'ICE seeks solutions for secure, reliable internet connectivity in remote border regions and mobile operations. Requirements include rapid deployment, encrypted communications, and support for field operations in areas with limited infrastructure.',
    requirements: [
      'Secure encrypted communications',
      'Rapid deployment capability',
      'Mobile and remote operation support',
      'High availability (99.5%+)',
      'Government security compliance',
      'Multi-device connectivity',
      'Real-time data transmission',
      'Weather-resistant equipment',
    ],
    keywords: [
      'border security',
      'remote connectivity',
      'mobile operations',
      'encrypted',
      'satellite',
      'field operations',
      'DHS',
      'law enforcement',
    ],
    priority: 'high',
    deadline: new Date('2024-12-31').toISOString(),
    uploaded_at: new Date('2024-03-01T10:00:00Z').toISOString(),
    processed: true,
  },
];
